tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      docker run -dp 1338:1338 -p 8089:8089 -v $PWD/tools:/home/tools --entrypoint /home/tools/start.sh --name octo-vehu yottadb/octo-vehu:latest-master


